### ISSUE TITLE
kindle-screensaver showing different information to /lovelace?kiosk

### ISSUE THREAD

**Issue by nokel** [sibbl/hass-lovelace-kindle-screensaver#98] opened 2023-12-08 05:06 UTC
Hi, I've got a really weird bug where the information that the kindle-screensaver shows is slightly different to what the actual link for /lovelace?kiosk is displaying and I have no idea why, or how to fix it?

/lovelace?kiosk
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/13248734/3f9f19d6-7884-4d5d-b660-25a2e60e3bb3)

kindle-screensaver
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/13248734/aae1abcb-3a8b-46be-8858-43b0e14f931a)

all of the modules seem to display correctly except the weather one, which seems to show the names of the days incorrectly? The scraper for the weather is the wunderground addon from https://github.com/cytech/Home-Assistant-wundergroundpws so I don't know if it's a bug on their end, or this one...

**Comment by sibbl** [comment] 2023-12-10 14:36
That's indeed a very interesting issue. My initial thought was that it could be a timing issue but the date and time are displayed equally in the other component.

Could you please try adding another weather provider and check if it's the same issue there?

I could imagine it will be the same problem then, which might indicate that it's rather an issue of the weather lovelace component.

**Comment by nokel** [comment] 2023-12-11 02:18
It looks like the default weather module shows the correct labels on both of the views... which is kind of odd...

/lovelace?kiosk
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/13248734/93ca41c7-e091-4a44-9f2d-bc4b311c0fe4)

kindle-screensaver
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/13248734/92a66068-2706-459a-aaaf-d3123958088c)

**Comment by jeeves5454** [comment] 2024-01-11 14:06
I have the same issue when using my standard forecast and it causes an issue with both Hourly and Daily levels. The Ecobee forecast does not see the same error. There is something wrong but unsure where to go next to diagnose. The issue is on Image creation though. It is not an exact replica of the Weather section either. 

![Dashboard](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/44647086/3ae82cc3-f163-496b-92a2-b1ececbb95a5)

![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/44647086/a51aca92-bf7b-4d9e-b3f2-aedcba7fc765)

Thank you for the hardwork. Looking forward to repurposing the Kindle :-)

**Comment by jeeves5454** [comment] 2024-01-11 14:09
Looking at other issues in the list I believe its a TimeZone issue. Will try with that and see if it resolves it.

**Comment by jeeves5454** [comment] 2024-01-11 14:20
Confirmed. Adding the TimeZone environment variable resolved the issue. My suggestion/Request - Add the TZ env variable to the instructions to support the install and close this issue. Thanks!!!

**Closed** 2024-01-21 10:04 UTC
